### ISSUE TITLE
Use backwards compatible super() calls

### ISSUE THREAD

**Issue by ambsw-technology** [Artory/drf-hal-json#16]
I tried the current version of master on a py2.7 project and had issues with the empty super calls.  I'll put together a PR, but want to draw attention to the issue to help avoid additional instances from being introduced in active branches.

**Comment by webjunkie** [comment]
@jstaffans What's our stance regarding py2 here?

**Comment by webjunkie** [comment]
Fixed in #17

**Comment by webjunkie** [comment]
Fixed in #17
