### ISSUE TITLE
Pagination links when there is only one page

### ISSUE THREAD

**Issue by jstaffans** [Artory/drf-hal-json#2]
```json
"_links": {
    "self": {
      "href": "http://localhost:8000/api/v1/customers"
    },
    "next": {
      "href": null
    },
    "previous": {
      "href": null
    }
  }
```

It would make more sense to leave out the `next` and `previous` relations entirely, if there are no links.

**Comment by David-Guillot** [comment]
:+1: , and it would be more compliant to [the hal RFC draft](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-5.1)
