### ISSUE TITLE
Add template to pagination for clients to generate pages

### ISSUE THREAD

**Issue by webjunkie** [Artory/drf-hal-json#23]
Add a link with `templated: true` for the pagination.

See example in <https://tools.ietf.org/html/draft-kelly-json-hal-08#section-6>

**Comment by jstaffans** [comment]
Correct me if I'm wrong, but the section of the specification that you linked to only mentions finding a specific Order per ID and does not have anything to do with pagination.

**Comment by webjunkie** [comment]
I put it as a reference for the templating. The section is called "Example Document" and shows an example with `"templated": true` which is what this PR talks about.
