### ISSUE TITLE
Split this fork off

### ISSUE THREAD

**Issue by webjunkie** [Artory/drf-hal-json#30]
As this fork most likely won't be merged back, we should consider asking Github to remove the fork linking and we should possibly also rename the project so that there are no two `drf-hal-json`.

See seebass/drf-hal-json#5

Ideas for names? @jstaffans @jakubartory?

**Comment by claytondaley** [comment]
What's the issue preventing a PR?  seabass seemed OK with it.

**Comment by jstaffans** [comment]
Our thinking was that continued maintenance is easier if we are in control of the repository and PyPI package.

**Comment by claytondaley** [comment]
Of course.  Has anyone asked for access to the existing PyPi package?  That would address the concern while providing continuity.
